//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowerTecEntities : DbContext
    {
        public PowerTecEntities()
            : base("name=PowerTecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBeneficio> tbBeneficio { get; set; }
        public virtual DbSet<tbCargo> tbCargo { get; set; }
        public virtual DbSet<tbChamado> tbChamado { get; set; }
        public virtual DbSet<tbDepartamento> tbDepartamento { get; set; }
        public virtual DbSet<tbDependente> tbDependente { get; set; }
        public virtual DbSet<tbFerias> tbFerias { get; set; }
        public virtual DbSet<tbFuncionario> tbFuncionario { get; set; }
        public virtual DbSet<tbFuncionarioBeneficio> tbFuncionarioBeneficio { get; set; }
        public virtual DbSet<tbHolerite> tbHolerite { get; set; }
        public virtual DbSet<tbPonto> tbPonto { get; set; }
    }
}
