//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBeneficio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBeneficio()
        {
            this.tbFuncionarioBeneficio = new HashSet<tbFuncionarioBeneficio>();
        }
    
        public int IdBeneficio { get; set; }
        public string Nome { get; set; }
        public string Empresa_prestadora { get; set; }
        public decimal Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFuncionarioBeneficio> tbFuncionarioBeneficio { get; set; }
    }
}
