//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using PowerTecWeb.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Cargo))]
    public partial class tbCargo
    {
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCargo()
        {
            this.tbFuncionario = new HashSet<tbFuncionario>();
        }
    
        public int IdCargo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public decimal Salario_base { get; set; }
        public string Beneficios { get; set; }
        public string Carga_horaria { get; set; }
        public Nullable<System.DateTime> Data_criacao { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
    
        public virtual tbDepartamento tbDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFuncionario> tbFuncionario { get; set; }
    }
}
