//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbChamado
    {
        public int IdChamado { get; set; }
        public string Assunto { get; set; }
        public string Mensagem { get; set; }

        [DisplayName("Data de chamado")]
        public System.DateTime Data_chamado { get; set; }

        [DisplayName("Funcionário")]
        public Nullable<int> IdFuncionario { get; set; }
    
        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}
