//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using PowerTecWeb.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(Dependentes))]
    public partial class tbDependente
    {
        public int IdDependente { get; set; }
        public string Nome { get; set; }
        public System.DateTime Data_nascimento { get; set; }
        public string Cpf { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
    
        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}
