//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbFerias
    {
        public int IdFerias { get; set; }

        [DisplayName("Data de inicio")]
        public System.DateTime Data_Inicio { get; set; }
        [DisplayName("Data de fim")]
        public System.DateTime Data_Fim { get; set; }
        public string Aprovado { get; set; }
        [DisplayName("Funcionário")]
        public Nullable<int> IdFuncionario { get; set; }
    
        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}
