//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using PowerTecWeb.Models;

    [MetadataType(typeof(Funcionario))]
    public partial class tbFuncionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFuncionario()
        {
            this.tbChamado = new HashSet<tbChamado>();
            this.tbDependente = new HashSet<tbDependente>();
            this.tbFerias = new HashSet<tbFerias>();
            this.tbFuncionarioBeneficio = new HashSet<tbFuncionarioBeneficio>();
            this.tbHolerite = new HashSet<tbHolerite>();
            this.tbPonto = new HashSet<tbPonto>();
        }
    
        public int IdFuncionario { get; set; }
        public string Nome_completo { get; set; }
        public string Cpf { get; set; }
        public string Rg { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Estado_civil { get; set; }
        public decimal Salario { get; set; }
        public System.DateTime Data_admissao { get; set; }
        public string Jornada_trabalho { get; set; }
        public string Tipo_contrato { get; set; }
        public string Banco_agencia { get; set; }
        public string Numero_conta { get; set; }
        public Nullable<int> NivelAcesso { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
    
        public virtual tbCargo tbCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChamado> tbChamado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDependente> tbDependente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFerias> tbFerias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFuncionarioBeneficio> tbFuncionarioBeneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHolerite> tbHolerite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPonto> tbPonto { get; set; }
    }
}
