//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbFuncionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFuncionario()
        {
            this.tbChamado = new HashSet<tbChamado>();
            this.tbDependente = new HashSet<tbDependente>();
            this.tbFerias = new HashSet<tbFerias>();
            this.tbFuncionarioBeneficio = new HashSet<tbFuncionarioBeneficio>();
            this.tbHolerite = new HashSet<tbHolerite>();
            this.tbPonto = new HashSet<tbPonto>();
        }
        
        public int IdFuncionario { get; set; }
        [DisplayName("Nome completo")]
        public string Nome_completo { get; set; }
        [DisplayName("CPF")]
        public string Cpf { get; set; }
        public string Rg { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        [DisplayName("Estado civil")]
        public string Estado_civil { get; set; }
        public decimal Salario { get; set; }

        [DisplayName("Data admissão")]
        public System.DateTime Data_admissao { get; set; }

        [DisplayName("Jornada de trabalho mensal")]
        public string Jornada_trabalho { get; set; }

        [DisplayName("Tipo de contrato")]
        public string Tipo_contrato { get; set; }
        [DisplayName("Agencia")]
        public string Banco_agencia { get; set; }
        [DisplayName("Numero da conta")]
        public string Numero_conta { get; set; }

        [DisplayName("Nivel de acesso")]
        public Nullable<int> NivelAcesso { get; set; }

        [DisplayName("Cargo")]
        public Nullable<int> IdCargo { get; set; }
        
        [DisplayName("Nivel de acesso")]
        public Nullable<int> IdEndereco { get; set; }
        
        public string Usuario { get; set; }
        public string Senha { get; set; }
    
        public virtual tbCargo tbCargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbChamado> tbChamado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDependente> tbDependente { get; set; }
        public virtual tbEndereco tbEndereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFerias> tbFerias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFuncionarioBeneficio> tbFuncionarioBeneficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHolerite> tbHolerite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPonto> tbPonto { get; set; }
    }
}
