//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFuncionarioBeneficio
    {
        public int IdFuncionarioBeneficio { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
        public Nullable<int> IdBeneficio { get; set; }
    
        public virtual tbBeneficio tbBeneficio { get; set; }
        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}
