//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerTecWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHolerite
    {
        public int IdHolerite { get; set; }
        public string Periodo { get; set; }
        public decimal Salario_base { get; set; }
        public decimal Horas_extras { get; set; }
        public decimal Comissoes { get; set; }
        public decimal Outros_proventos { get; set; }
        public decimal Total_proventos { get; set; }
        public decimal Plano_saude { get; set; }
        public Nullable<decimal> Vale_transporte { get; set; }
        public Nullable<decimal> Total_deducoes { get; set; }
        public decimal Valor_liquido { get; set; }
        public decimal Ferias { get; set; }
        public Nullable<decimal> Aviso_previo { get; set; }
        public decimal Beneficios_adicionais { get; set; }
        public string Outras_Informacoes { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
    
        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}
